version: '3.8'

services:
  backend:
    build:
      context: ./P13-chat-backend
      dockerfile: Dockerfile
    container_name: springboot-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
    restart: always

  frontend:
    build:
      context: ./P13-chat-frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
