version: '3.8'

services:
  backend:
    build:
      context: ./P13-chat-backend
      dockerfile: Dockerfile
    ports:
      - "3555:3555"
      - "8085:8085"
    networks:
      - app-network

  frontend:
    build:
      context: ./P13-chat-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
